- hosts: proxy
  become: yes
  tasks:
   - name: "install nginx"
     apt:
       name:
         - nginx
         - net-tools
         - mc
       state: latest
       update_cache: yes

   - name: "delete default nginx symlink"
     file:
       path: "/etc/nginx/sites-enabled/default"
       state: absent

   - name: "copy reverse proxy config from templates"
     template:
       src: reverse-proxy.conf
       dest: "/etc/nginx/sites-available/reverse-proxy.conf"
       owner: root
       group: root
       mode: '0644'

   - name: "create symlink for proxy config file"
     file:
       src: "/etc/nginx/sites-available/reverse-proxy.conf"
       dest: "/etc/nginx/sites-enabled/reverse-proxy.conf"
       state: link
     notify: restart nginx
   
  handlers:
   - name: restart nginx
      service:
        name: nginx
        state: restarted
